import * as actions from '../actions/index';
import autoScroll from '../auto-scroll/index';
import interactablePreventDefault from '../core/interactablePreventDefault';
import inertia from '../inertia/index';
import modifiersBase from '../modifiers/base';
import * as pointerEvents from '../pointer-events/index';
import reflow from '../reflow/index';
import interact from './interact';
export declare function init(window: Window): import("@interactjs/interact/interact").InteractStatic;
export default interact;
export { interact, actions, autoScroll, interactablePreventDefault, inertia, modifiersBase as modifiers, pointerEvents, reflow, };
