import * as arr from './arr';
import * as dom from './domUtils';
import * as is from './is';
import win from './window';
export declare function warnOnce(method: any, message: any): () => any;
export declare function _getQBezierValue(t: any, p1: any, p2: any, p3: any): number;
export declare function getQuadraticCurvePoint(startX: any, startY: any, cpX: any, cpY: any, endX: any, endY: any, position: any): {
    x: number;
    y: number;
};
export declare function easeOutQuad(t: any, b: any, c: any, d: any): any;
export declare function copyAction(dest: any, src: any): any;
export { default as browser } from './browser';
export { default as clone } from './clone';
export { default as events } from './events';
export { default as extend } from './extend';
export { default as getOriginXY } from './getOriginXY';
export { default as hypot } from './hypot';
export { default as normalizeListeners } from './normalizeListeners';
export { default as pointer } from './pointerUtils';
export { default as raf } from './raf';
export { default as rect } from './rect';
export { default as Signals } from './Signals';
export { win, arr, dom, is, };
