import pointerExtend from './pointerExtend';
export declare function copyCoords(dest: Interact.CoordsSetMember, src: Interact.CoordsSetMember): void;
export declare function setCoordDeltas(targetObj: Interact.CoordsSetMember, prev: Interact.CoordsSetMember, cur: Interact.CoordsSetMember): void;
export declare function setCoordVelocity(targetObj: Interact.CoordsSetMember, delta: Interact.CoordsSetMember): void;
export declare function setZeroCoords(targetObj: Interact.CoordsSetMember): void;
export declare function isNativePointer(pointer: any): boolean;
export declare function getXY(type: any, pointer: any, xy: any): any;
export declare function getPageXY(pointer: Interact.PointerType | Interact.InteractEvent, page?: Interact.Point): import("@interactjs/types/types").Point;
export declare function getClientXY(pointer: any, client: any): any;
export declare function getPointerId(pointer: any): any;
export declare function setCoords(targetObj: any, pointers: any[], timeStamp: number): void;
export declare function getTouchPair(event: any): any[];
export declare function pointerAverage(pointers: PointerEvent[] | Event[]): {
    pageX: number;
    pageY: number;
    clientX: number;
    clientY: number;
    screenX: number;
    screenY: number;
};
export declare function touchBBox(event: Event | Array<(Interact.PointerType) | TouchEvent>): {
    x: number;
    y: number;
    left: number;
    top: number;
    right: number;
    bottom: number;
    width: number;
    height: number;
};
export declare function touchDistance(event: any, deltaSource: any): number;
export declare function touchAngle(event: any, deltaSource: any): number;
export declare function getPointerType(pointer: any): any;
export declare function getEventTargets(event: any): import("@interactjs/types/types").Element[];
export declare function newCoords(): Interact.CoordsSetMember;
export declare function coordsToEvent(coords: MockCoords): ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & MouseEvent) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & MouseEvent & PointerEvent) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & MouseEvent & import("@interactjs/pointer-events/PointerEvent").default<any>) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & MouseEvent & import("@interactjs/core/InteractEvent").InteractEvent<never, "end" | "resume" | "start" | "move" | "inertiastart" | "reflow">) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & MouseEvent & TouchEvent) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & Touch & MouseEvent) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & Touch & PointerEvent) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & Touch & import("@interactjs/pointer-events/PointerEvent").default<any>) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & Touch & import("@interactjs/core/InteractEvent").InteractEvent<never, "end" | "resume" | "start" | "move" | "inertiastart" | "reflow">) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & Touch & TouchEvent) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & PointerEvent & MouseEvent) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & PointerEvent) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & PointerEvent & import("@interactjs/pointer-events/PointerEvent").default<any>) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & PointerEvent & import("@interactjs/core/InteractEvent").InteractEvent<never, "end" | "resume" | "start" | "move" | "inertiastart" | "reflow">) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & PointerEvent & TouchEvent) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & import("@interactjs/pointer-events/PointerEvent").default<any> & MouseEvent) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & import("@interactjs/pointer-events/PointerEvent").default<any> & PointerEvent) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & import("@interactjs/pointer-events/PointerEvent").default<any>) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & import("@interactjs/pointer-events/PointerEvent").default<any> & import("@interactjs/core/InteractEvent").InteractEvent<never, "end" | "resume" | "start" | "move" | "inertiastart" | "reflow">) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & import("@interactjs/pointer-events/PointerEvent").default<any> & TouchEvent) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & import("@interactjs/core/InteractEvent").InteractEvent<never, "end" | "resume" | "start" | "move" | "inertiastart" | "reflow"> & MouseEvent) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & import("@interactjs/core/InteractEvent").InteractEvent<never, "end" | "resume" | "start" | "move" | "inertiastart" | "reflow"> & PointerEvent) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & import("@interactjs/core/InteractEvent").InteractEvent<never, "end" | "resume" | "start" | "move" | "inertiastart" | "reflow"> & import("@interactjs/pointer-events/PointerEvent").default<any>) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & import("@interactjs/core/InteractEvent").InteractEvent<never, "end" | "resume" | "start" | "move" | "inertiastart" | "reflow">) | ({
    coords: MockCoords;
    readonly page: any;
    readonly client: any;
    readonly timeStamp: any;
    readonly pageX: any;
    readonly pageY: any;
    readonly clientX: any;
    readonly clientY: any;
    readonly pointerId: any;
    readonly target: any;
    readonly type: any;
    readonly pointerType: any;
    readonly buttons: any;
    preventDefault(): void;
} & import("@interactjs/core/InteractEvent").InteractEvent<never, "end" | "resume" | "start" | "move" | "inertiastart" | "reflow"> & TouchEvent);
export interface MockCoords {
    page: Interact.Point;
    client: Interact.Point;
    timeStamp?: number;
    pointerId?: any;
    target?: any;
    type?: string;
    pointerType?: string;
    buttons?: number;
}
export { pointerExtend };
